# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --output ./output
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Output Test Results
      run: |
        mkdir -p test-results
        find . -name 'TestResults' -exec cp -r {} test-results/ \;
      continue-on-error: true
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-linux
        path: test-results
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-linux
        path: ./output

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --output ./output
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Output Test Results
      run: |
        mkdir test-results
        Get-ChildItem -Recurse -Filter 'TestResults' | ForEach-Object { Copy-Item $_.FullName -Destination test-results -Recurse }
      continue-on-error: true
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results-windows
        path: test-results
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts-windows
        path: ./output
